spring.application.name=food-voting-winner
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:foodvotingwinner
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
